export const SPECIALTIES = [
  {
    id: 'vanguard',
    name: 'Vanguard Spear',
    color: 0xffc26b,
    description: 'Steady duelist. Bonus damage at close range.',
    minDamage: 10,
    maxDamage: 16,
    range: 52,
    splash: false,
  },
  {
    id: 'strategist',
    name: 'Strategist Fan',
    color: 0x7bc7ff,
    description: 'Wide strike. Hits all nearby enemies.',
    minDamage: 7,
    maxDamage: 11,
    range: 65,
    splash: true,
  },
  {
    id: 'shadow',
    name: 'Shadow Blades',
    color: 0xd89cff,
    description: 'Short reach. High crit chance.',
    minDamage: 8,
    maxDamage: 14,
    range: 42,
    splash: false,
    critChance: 0.3,
  },
];

export const NPCS = [
  {
    id: 'songjiang',
    x: 7,
    y: 8,
    name: '宋江',
    role: 'Song Jiang',
    dialog: 'Stranger. The mountain accepts those who prove their worth — and only those. Help the road, then I will speak of the road home.',
    recruitable: true,
  },
  {
    id: 'wuyong',
    x: 11,
    y: 7,
    name: '吴用',
    role: 'Wu Yong',
    dialog: 'I have read every chronicle in three provinces, and none of them describe a man like you. Modern speech. Strange shoes. The old texts say a tear in fate sometimes pulls a soul backward. Prove your blade and I will help you map the way back.',
    recruitable: false,
  },
  {
    id: 'linchong',
    x: 9,
    y: 10,
    name: '林冲',
    role: 'Lin Chong',
    dialog: 'They took my wife. The magistrate\'s men dragged her behind their walls because I would not bow. I will burn that fortress to ash. Walk with me to it — when the raiders here are dust.',
    recruitable: true,
  },
  {
    id: 'villager',
    x: 30,
    y: 10,
    name: '刘村民',
    role: 'Village Elder Liu',
    dialog: 'They came at dawn. Burned the granary, took the young men for the magistrate\'s levy. Their captain still stalks the road — Zhao, with the iron mask. End him and the road south reopens.',
    recruitable: false,
  },
  {
    id: 'tonkey',
    x: 12,
    y: 12,
    name: 'Tonkey',
    role: 'Wandering Fighter',
    dialog: "Name's Tonkey. You look like you just woke from a fever dream. Need backup? I'll run with you.",
    recruitable: false,
  },
  // ── Scattered Liangshan heroes to recruit ──
  {
    id: 'chaogai',
    x: 5, y: 5,
    name: '托塔天王',
    role: 'Chao Gai',
    dialog: 'I built the Liangshan oath with my own hands. The road you walk is the road we walked.',
    recruitable: true,
  },
  {
    id: 'huarong',
    x: 16, y: 6,
    name: '小李广',
    role: 'Hua Rong, Archer',
    dialog: 'My bow finds its mark before the enemy finds breath. Stand with us and the road home opens wider.',
    recruitable: true,
  },
  {
    id: 'likui',
    x: 3, y: 12,
    name: '黑旋风',
    role: 'Li Kui',
    dialog: 'You smell like fresh trouble. Good! I was tired of waiting.',
    recruitable: true,
  },
  {
    id: 'lujunyi',
    x: 8, y: 4,
    name: '玉麒麟',
    role: 'Lu Junyi',
    dialog: 'A jade qilin is patient. Show me your skill before you show me your story.',
    recruitable: true,
  },
  {
    id: 'guansheng',
    x: 17, y: 8,
    name: '大刀',
    role: 'Guan Sheng',
    dialog: 'A great blade honors a great cause. State yours.',
    recruitable: true,
  },
  {
    id: 'huyanzhuo',
    x: 20, y: 11,
    name: '双鞭',
    role: 'Hu Yanzhuo',
    dialog: 'Two whips, one rider. The magistrate fears both. You should fear neither.',
    recruitable: true,
  },
  {
    id: 'andaoquan',
    x: 6, y: 14,
    name: '神医',
    role: 'An Daoquan',
    dialog: 'Step closer. That wound on your sword arm — let me see it before it festers.',
    recruitable: false,
  },
  {
    id: 'shiqian',
    x: 14, y: 13,
    name: '鼓上蚤',
    role: 'Shi Qian',
    dialog: 'You did not see me approach. That is the point. Let me know if you need a lock opened.',
    recruitable: false,
  },
  // Lin Chong's wife — appears only after Warlord Gao falls. Placed where the
  // warlord stood, behind the magistrate's wall.
  {
    id: 'linchongwife',
    x: 45, y: 1, // ≈ world (65, 34.5), near where Warlord Gao spawns
    name: '林娘子',
    role: "Lin Chong's Wife",
    dialog: 'You broke the gate. He sent you, didn\'t he. Tell him I am whole. Tell him the lantern is still lit, and I will walk back with him beside me.',
    recruitable: false,
    hiddenUntil: 'warlord_dead',
  },
  // ── Expanded roster: 15 more wandering Liangshan-bound heroes ──
  // Tile positions scatter across the open world; dialog lines are original
  // short prose written for this game.
  {
    id: 'husanniang', x: -5, y: 8,
    name: '一丈青', role: 'Hu Sanniang',
    dialog: 'A woman with two sabers asks fewer questions and lands more strikes. Ride beside me — you will see.',
    recruitable: true,
  },
  {
    id: 'wusong', x: 22, y: 4,
    name: '武松', role: 'Wu Song',
    dialog: 'Tigers fall to a single fist if the fist is honest. So do magistrates. Come — I have rice wine.',
    recruitable: true,
  },
  {
    id: 'yanqing', x: 28, y: 12,
    name: '浪子', role: 'Yan Qing',
    dialog: 'I sing better than I shoot, and I shoot better than most. Bring me a song worth keeping.',
    recruitable: true,
  },
  {
    id: 'daizong', x: 4, y: 16,
    name: '神行太保', role: 'Dai Zong',
    dialog: 'Three hundred li before noon. Tell me where you need word carried, stranger.',
    recruitable: true,
  },
  {
    id: 'ruanxiaowu', x: 35, y: 4,
    name: '短命二郎', role: 'Ruan Xiaowu',
    dialog: 'We Ruan brothers do not bow on land. Less so on water. Keep your boots dry, friend.',
    recruitable: false,
  },
  {
    id: 'lijun', x: 35, y: 6,
    name: '混江龙', role: 'Li Jun',
    dialog: 'The river hears every secret. Walk with me long enough and it tells me yours.',
    recruitable: false,
  },
  {
    id: 'qinming', x: 25, y: 9,
    name: '霹雳火', role: 'Qin Ming',
    dialog: 'The magistrate\'s iron melts under a long enough hammer. Mine has been swinging since dawn.',
    recruitable: true,
  },
  {
    id: 'dongping', x: -12, y: 10,
    name: '双枪将', role: 'Dong Ping',
    dialog: 'Two spears, one wrist. Stay clear of the second.',
    recruitable: true,
  },
  {
    id: 'sunerniang', x: -8, y: 14,
    name: '母夜叉', role: 'Sun Erniang',
    dialog: "Inn's full of bones. Don't ask. Sit. Drink. Then we'll talk about your road.",
    recruitable: false,
  },
  {
    id: 'zhutong', x: 20, y: 2,
    name: '美髯公', role: 'Zhu Tong',
    dialog: 'My beard has seen four magistrates fall and none deserved it. Yours will be the fifth.',
    recruitable: true,
  },
  {
    id: 'xuning', x: 3, y: 5,
    name: '金枪手', role: 'Xu Ning',
    dialog: 'Family spear. Family debt. Help me settle both and Liangshan grows stronger.',
    recruitable: true,
  },
  {
    id: 'liutang', x: -2, y: 13,
    name: '赤发鬼', role: 'Liu Tang',
    dialog: 'Red hair, red road. I do not stop until the magistrate\'s gate is red too.',
    recruitable: true,
  },
  {
    id: 'zhangshun', x: 38, y: 9,
    name: '浪里白条', role: 'Zhang Shun',
    dialog: 'I learned to fight where boots cannot follow. The river is on your side if I am.',
    recruitable: false,
  },
  {
    id: 'shixiu', x: 1, y: 4,
    name: '拼命三郎', role: 'Shi Xiu',
    dialog: 'I have nothing to go back to. So I never look back. Lead, and I follow until one of us drops.',
    recruitable: true,
  },
  {
    id: 'baisheng', x: 18, y: 15,
    name: '白日鼠', role: 'Bai Sheng',
    dialog: 'I sold wine to seven guards before they realized the seal was forged. What do you need taken?',
    recruitable: false,
  },
];

export const INITIAL_CHAPTER_STATE = {
  chapter: 1,
  stage: 'clear_raiders',
  objective: 'Defeat raiders to progress (0/5). Captain Zhao awaits.',
  completed: false,
  raidersDefeated: 0,
  raidersTarget: 5,
  minibossSpawned: false,
  minibossDefeated: false,
};

export const CHAPTER2_STATE = {
  chapter: 2,
  stage: 'clear_guards',
  objective: 'Defeat the Magistrate\'s guards (0/7). The Warlord hides within.',
  completed: false,
  raidersDefeated: 0,
  raidersTarget: 7,
  minibossSpawned: false,
  minibossDefeated: false,
};
